name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install PlatformIO
      run: |
        pip install platformio
        
    - name: Build Firmware
      run: |
        cd firmware
        pio run
        
    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        name: firmware-binaries
        path: |
          firmware/.pio/build/esp32dev/firmware.bin
          firmware/.pio/build/esp32dev/spiffs.bin
