name: Build ESP32

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        echo "Binary files akan di-generate manual"
        echo "firmware.bin dan spiffs.bin"
