name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PlatformIO
      uses: platformio/setup-platformio@v2
      
    - name: Build Project
      run: |
        cd firmware
        pio run
        
    - name: Upload Firmware Binaries
      uses: actions/upload-artifact@v4
      with:
        name: spot-welder-firmware
        path: |
          firmware/.pio/build/esp32dev/firmware.bin
          firmware/.pio/build/esp32dev/spiffs.bin
        retention-days: 30
